_keys:
  _root_keys:
  - info
  - global
  - noise_reducer
  - suggest_bads
  - bads_to_hdf
  - interpolate_bads
  - ica
  - epocher
  - report
  _sorted_keys:
  - run
  - overwrite
  - save
  - plot
  - plot_show
  - plot_dir
bads_to_hdf:
  hdfname: jumeg_intext_badchannel_info.hdf
  run: false
epocher:
  _sorted_keys:
  - do_events
  - do_epochs
  conditions: None
  do_epochs: false
  do_events: false
  overwrite: false
  run: false
  save: true
  template: None
filter_1:
  fhigh: 120.0
  file_extention:
  - ar-raw.fif
  - ar-empty.fif
  flow: 0.1
  overwrite: false
  postfix: fi
  run: false
  save: true
  type: mne
global:
  _sorted_keys:
  - experiment
  - subjects
  - stage
  - file_extention
  - recursive
  experiment: INTEXT
  file_extention:
  - meeg-raw.fif
  - rfDC-empty.fif
  recursive: true
  subjects: None
ica:
  chops:
    description: ica-chops
    length: 120.0
    show: false
    time_window:
    - 5.0
    - 5.0
  ecg:
    ch_name: ECG
    event_id: 999
    fhigh: 20
    flow: 8
    thresh: 0.3
    tmax: 0.4
    tmin: -0.4
    use_jumeg: true
  eog:
    ch_name:
    - EOG ver
    event_id:
    - 997
    fhigh: 20
    flow: 1
    hor_ch: EOG hor
    thresh: 0.2
    tmax: 0.6
    tmin: -0.6
    use_jumeg: true
    ver_ch: EOG ver
  exclude: bads
  file_extention:
  - ',nr,bcc,int-raw.fif'
  - rfDC,nr,bcc,int-empty.fif
  fit:
    _sorted_keys:
    - plot_sources
    overwrite: false
    save: false
    use_artifact_rejection: true
    use_svm: false
  overwrite: false
  plot_dir: report
  postfix: ar
  pre_filter:
    fhigh: 45.0
    flow: 0.1
    overwrite: false
    run: true
    save: false
  random_state: 42
  reject:
    mag: 6.0e-11
  run: true
  transform:
    _sorted_keys:
    - filtered
    - unfiltered
    filtered:
      run: true
      save: true
      save_chop: false
      save_chop_clean: false
    run: true
    unfiltered:
      run: true
      save: true
      save_chop: false
      save_chop_clean: false
info:
  gui-version: 2020.03.11.001
  python-version: 3.6.10
  time: 2020-04-23 16:23
  user: fboers
interpolate_bads:
  _sorted_keys:
  - plot_block
  file_extention:
  - ',nr,bcc-raw.fif'
  - rfDC,nr,bcc-empty.fif
  hdfname: jumeg_badchannel_info.hdf
  overwrite: false
  plot_block: false
  postfix: int
  run: false
  save: true
noise_reducer:
  file_extention:
  - meeg-raw.fif
  - rfDC-empty.fif
  fmax: 300
  noiseref_hp:
  - RFG ...
  overwrite: false
  plot: true
  plot_dir: report
  plot_show: false
  postfix: nr
  refhp: 0.1
  reflp: 5.0
  refnotch:
  - 50.0
  - 100.0
  - 150.0
  - 200.0
  - 250.0
  - 300.0
  - 350.0
  - 400.0
  run: false
  save: true
report:
  _sorted_keys:
  - noise_reducer
  - ica
  - epocher
  epocher:
    extention: ep.png
    run: false 
  ica:
    extention: ar.png
    run: true
  noise_reducer:
    extention: nr-raw.png
    run: true
  overwrite: true
  path: report
  run: true
  save: true
suggest_bads:
  file_extention:
  - ',nr-raw.fif'
  - rfDC,nr-empty.fif
  fmax: 100
  overwrite: false
  parameter:
    epoch_length: None
    fraction: 0.001
    sensitivity_psd: 95
    sensitivity_steps: 97
    show_raw: false
    summary_plot: false
    validation: true
  plot: false
  plot_show: false
  postfix: bcc
  run: false
  save: true
